### ISSUE TITLE
As a user I would like to see quality badges on the project homepage (README)

### ISSUE THREAD

**Issue by arikkfir** [arikkfir/greenstar#251]
There are a multitude of quality badges we can add to the project README.md for new users:

- Build status
- Go report card
- TypeScript related badges (need to research)
- More...?

**Comment by that-ar-guy** [comment]
hey @arikkfir  can i take this one. I am new to open source and would like to try it.

**Comment by arikkfir** [comment]
Hi, sure thing, go ahead!
